@echo off
SET XELATEX="C:\Users\Besitzer\AppData\Local\Programs\MiKTeX\miktex\bin\x64\xelatex.exe"
echo [1/2] First pass...
%XELATEX% -interaction=nonstopmode main.tex
echo [2/2] Second pass (TOC + cross-refs)...
%XELATEX% -interaction=nonstopmode main.tex
echo Done! Opening PDF...
start "" main.pdf
